Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
NumericLiterals:
  MinDigits: 10
AbcSize:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false

Style/SymbolProc
  Enabled: false

Style/Next:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 200